#!/bin/sh

# generated by https://github.com/jeffsanc/auto.git

export my_CUR_FOLDER=$(pwd);
echo "Going to ROS workspace folder:"$ROS_CATKINWS_NAME
cd ~/$ROS_CATKINWS_NAME && catkin_make;
cd $my_CUR_FOLDER;
echo "Returning back to previous folder:":$my_CUR_FOLDER
